### PR TITLE
Include prior current/undeleted documents in conflicts

### PR DESCRIPTION
**Pull request by lambmj**
I had designed a view to keep track of conflicts using the recently added`_conflicts` property.  I found that some conflicts weren't being passed to my view's map function.  Looking at the TDView.m (lines 218-223) it appears that only conflicts included in the current re-indexing (sequence>lastSequence) were noted as conflicts and passed in the `_conflicts` property.  I added code to find and include conflicts that were included in previous indexing attempts.

### CODE REVIEW

**Comment by snej** [comment]
I see the problem, but I'm concerned that this fix is too slow — it adds another SQL query for each new revision being indexed. I can't, offhand, think of a faster way to do it, though.
It would be OK if this query only happened for revisions that have conflicts, but there's no way to determine that in the current schema. I've thought of adding a "hasConflict" flag to the 'docs' table, but that would be somewhat tricky to keep up to date.

**Comment by snej** [comment]
The query can be optimized a bit since we already know the doc_id. Also, ordering doesn't matter.

```
r2 = [fmdb executeQuery: @"SELECT revid FROM revs "
"WHERE doc_id=? AND sequence<=? AND current!=0 AND deleted=0",
$object(doc_id), $object(lastSequence)];
```

Also, this query only needs to be done at all if lastSequence > 0, i.e. not on the first time the view is indexed.

Can you try that, and see if it still finds all conflicts and if all the unit tests still pass?

**Comment by lambmj** [comment]
Sure thing.  I was concerned about the efficiency of the query but didn't know how best to optimize it.

**Comment by lambmj** [comment]
Yes, the changes work and all the units test passed.

**Comment by snej** [comment]
OK, I squashed your two commits together and pushed them as 7af0f2555f745cc6200953835f8c5010356480e3. Thanks!

**Pull request closed without merging**
