### PR TITLE
Clean up prefix header for CocoaPods compatibility

### PR DESCRIPTION
**Pull request by mullr**
I've been working on getting CouchCocoa and TouchDB working with CocoaPods. TouchDB in particular has some problems I had to work around. This fixes one of them; I'll file issues for the others.

### CODE REVIEW

**Comment by snej** [comment]
Sorry, I don't want to do this. The point of the prefix header is to speed up compilation and remove the need to add all these boilerplate includes to all the source files.

Can you explain why the prefix header causes problems with CocoaPods?

**Comment by snej** [comment]
FYI, it's best to talk it over with me first before embarking on a patch that will require changes to lots of source files.

**Comment by mullr** [comment]
CocoaPods works by making a single xcode project which contains the code for all the Pods you depend on. It has facilities for merging in prefix headers, but they apply then in the context of that composite project. So conflicts are possible. 

The conflict in this case is with the definition of $equal, which is defined by MYUtilities/CollectionUtils.h as 

`BOOL $equal(id obj1, id obj2);`

and in CouchCocoa/RESTInternal.h as 

`static inline BOOL $equal(id a, id b)`

Since the prefix header also effectively applies to CouchCocoa, the definitions conflict.

**Comment by snej** [comment]
> CocoaPods works by making a single xcode project which contains the code for all the Pods you depend on. 

Isn't that what workspaces are for?

> It has facilities for merging in prefix headers, but they apply then in the context of that composite project.

It tries to build a single prefix header by merging together prefixes from multiple independent libraries? That's totally insane; you can't do that and expect things to work. And it's unnecessary, since every target can have its own independent prefix.

**Comment by snej** [comment]
I looked at their website but couldn't find any information about the way it actually builds things. The only clue is that a podspec contains a list of source files, so it sounds as though they're trying to dump every single pod you use into a single _target_ and building it. Which is even more insane. I mean, package management like this is a good idea, but the way they're going about it seems kind of hopelessly naive. Maybe I'm just used to working on bigger and more complex projects than they are.

**Comment by mullr** [comment]
I can't disagree with anything you say. Separate projects (or targets) would be a better approach. Nonetheless, this is what's happening, and it seems to be pretty popular. 

I've been able to patch around the problems I encountered without too many problems with a post-installation script. It's rather ugly but it works. You can take a look if you like: 

https://github.com/CocoaPods/Specs/blob/master/TouchDB/0.961/TouchDB.podspec

I'll try to maintain these as you release newer versions of TouchDB/CouchCocoa, at the very least up until 1.0.

**Pull request closed without merging**
