### PR TITLE
Change to be able to pass custom request headers on all requests.

### PR DESCRIPTION
**Pull request by drekka**
- Added options request headers to sync code.
- Added authorisation to socket change tracker.

The essence of this commit was to be able to specify additional headers such as User-Agent which are added to all server request during a sync. These headers are passed as a dictionary to the TReplicator which passes them on to the various replicator classes.

### CODE REVIEW

**Comment by snej** [comment]
This looks pretty good, but how do you intend for apps to set the TDReplicator.requestHeaders property? I'd rather apps didn't touch the TDxxx classes directly.

**Comment by snej** [comment]
I'm making some revisions, mostly just for style.

You're using -addValue:forHTTPHeaderField:, which has a sort of weird behavior if a header with that name already exists — it just appends a comma and the string to the existing header value, instead of replacing the old value. Did you mean to use -setValue:forHTTPHeaderField: instead? That's the behavior you use in TDSocketChangeTracker.

**Comment by snej** [comment]
OK, I made some changes/fixes and merged it. Thanks!

**Comment by drekka** [comment]
Sorry, didn't get time to come back to your questions over the weekend. Not sure if they are still relevant but:

I added to TDReplicator because I used the following code in my project to do a replication:

```
[server tellTDDatabaseNamed:DATABASE to:^(TDDatabase *database) {

    TDReplicator *replicator = [database replicatorWithRemoteURL:sourceSyncURL 
                                                            push:NO 
                                                      continuous:NO];
    NSURLCredential *credentials = [[[NSURLCredential alloc] initWithUser:[[AppSettings sharedInstance] sourceSyncUsername]  
                                                                 password:[[AppSettings sharedInstance] sourceSyncPassword]  
                                                              persistence:NSURLCredentialPersistencePermanent] autorelease];
    TDBasicAuthorizer *authorizer = [[[TDBasicAuthorizer alloc] initWithCredential:credentials] autorelease];
    replicator.authorizer = authorizer;

    // Add custom headers for routing purposes.
    NSDictionary *requestHeaders = [NSDictionary dictionaryWithObjectsAndKeys:syncUserAgent, @"User-Agent", nil];
    replicator.requestHeaders = requestHeaders;

    replicator.filterName = @"docList/filter";
    replicator.filterParameters = [NSDictionary dictionaryWithObjectsAndKeys:wNumber, @"userId", nil];
    [replicator start];
}];
```

Is there a better way to start a replication, set security and headers for requests?

Regards the second quest about setting the headers, I tried to match your code with regard to setting headers. This was fairly new for me so I was not sure if I could use the same functions in both the higher apis and the lower ones. NS\* vs CF*.

**Comment by snej** [comment]
As of today, you can set basic-auth credentials and extra headers directly from CouchCocoa. Give it a try.

**Pull request closed without merging**
